### ISSUE TITLE
How can I run this docker image through docker-compose? 

### ISSUE THREAD

**Issue by tablenchair** [nerdalert/iperf3#10]
I would like to run this image alongwith others in docker-compose. How can I configure it to run in server-mode in the docker-compose file ? 
Also, is there anyway to bind it to an interface & specify the pid location, ie, options **-B** & **-I** respectively in [https://iperf.fr/iperf-doc.php#3doc](url)

**Comment by BBaoVanC** [comment]
Here's what my docker-compose.yml looks like:

```yml
version: "3"
services:
  iperf3:
    image: networkstatic/iperf3:latest
    restart: always
    ports:
      - 5201:5201
    command: -s
```
